## Conceito de n-grams

In [63]:
frase = "O amor é lido o amor é forte e o amor vence tudo"

In [64]:
palavras = frase.split()
palavras

['O',
 'amor',
 'é',
 'lido',
 'o',
 'amor',
 'é',
 'forte',
 'e',
 'o',
 'amor',
 'vence',
 'tudo']

In [65]:
import pandas as pd
tabela = pd.DataFrame({"palavra":palavras})
tabela

   palavra
0        O
1     amor
2        é
3     lido
4        o
5     amor
6        é
7    forte
8        e
9        o
10    amor
11   vence
12    tudo

In [66]:
tabela["proxima_palavra"] = tabela["palavra"].shift(-1)
tabela

   palavra proxima_palavra
0        O            amor
1     amor               é
2        é            lido
3     lido               o
4        o            amor
5     amor               é
6        é           forte
7    forte               e
8        e               o
9        o            amor
10    amor           vence
11   vence            tudo
12    tudo            None

In [67]:
tabela = tabela.dropna()
tabela

   palavra proxima_palavra
0        O            amor
1     amor               é
2        é            lido
3     lido               o
4        o            amor
5     amor               é
6        é           forte
7    forte               e
8        e               o
9        o            amor
10    amor           vence
11   vence            tudo

In [71]:
filtro = tabela["palavra"] =="é"
tabela[filtro]

  palavra proxima_palavra
2       é            lido
6       é           forte

In [69]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
lido     0.5
forte    0.5
Name: proportion, dtype: float64

In [70]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'lido'