In [40]:
arquivo = open(r"data\dom_casmurro.txt",encoding="utf-8")
texto = arquivo.read()

In [41]:
palavras = texto.split()
len(palavras)

65707

In [42]:
import pandas as pd
tabela = pd.DataFrame({"palavra":palavras})
tabela.head()

    palavra
0       DOM
1  CASMURRO
2       POR
3   MACHADO
4        DE

In [43]:
import pandas as pd
tabela = pd.DataFrame({"palavra":palavras})
tabela

        palavra
0           DOM
1      CASMURRO
2           POR
3       MACHADO
4            DE
...         ...
65702         É
65703      bem,
65704         e
65705         o
65706    resto?

[65707 rows x 1 columns]

In [44]:
tabela["proxima_palavra"] = tabela["palavra"].shift(-1)
tabela

        palavra proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65702         É            bem,
65703      bem,               e
65704         e               o
65705         o          resto?
65706    resto?            None

[65707 rows x 2 columns]

In [45]:
tabela = tabela.dropna()
tabela

        palavra proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65701   CXLVIII               É
65702         É            bem,
65703      bem,               e
65704         e               o
65705         o          resto?

[65706 rows x 2 columns]

In [62]:
filtro = tabela["palavra"] =="CXLVIII"
tabela[filtro]

       palavra proxima_palavra
64941  CXLVIII               E
65701  CXLVIII               É

In [63]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
E    0.5
É    0.5
Name: proportion, dtype: float64

In [64]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'E'